### ISSUE TITLE
可以提供用pyflink做机器学习的demo吗？

### ISSUE THREAD

**Issue by searchlink** [HuangXingBo/pyflink-demo#1]

**Comment by searchlink** [comment]
感谢分享的代码，收获很多，类似Derby，写入mysql，自定义connector如下：
```
mysql_connector = CustomConnectorDescriptor('jdbc', 0, False) \
                        .property('connector.driver', 'com.mysql.jdbc.Driver') \
                        .property('connector.url', 'jdbc:mysql://172.16.4.26:3306/flink') \
                        .property('connector.table', 'pv_uv_table') \
                        .property('connector.username', 'root') \
                        .property('connector.passwd', '8610912')    \
                        .property("connector.write.flush.max-rows", "1")
```
同时将mysql-connector-java-5.1.48.jar复制到pyflink/lib下，但是报错。报错如下：
```
Traceback (most recent call last):
  File "/home/wangwei/myPyFlink/flink/kafka_flink/kafka_flink_mysql.py", line 74, in <module>
    ).register_table_sink("sink")
  File "/home/wangwei/miniconda3/envs/flink/lib/python3.6/site-packages/pyflink/table/descriptors.py", line 1281, in register_table_sink
    self._j_connect_table_descriptor = self._j_connect_table_descriptor.registerTableSink(name)
  File "/home/wangwei/miniconda3/envs/flink/lib/python3.6/site-packages/py4j/java_gateway.py", line 1286, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/wangwei/miniconda3/envs/flink/lib/python3.6/site-packages/pyflink/util/exceptions.py", line 154, in deco
    raise exception_mapping[exception](s.split(': ', 1)[1], stack_trace)
pyflink.util.exceptions.TableException: 'findAndCreateTableSink failed.'
```
报错原因什么？还不大懂，另外能提供一点用pyflink做机器学习的demo吗？

**Comment by searchlink** [comment]
非常感谢分享的代码，收获颇多，希望您能继续完善更多的例子，同时能提供用pyflink进行机器学习的例子

**Comment by hyclimb** [comment]
我也正在学这块，例子很实用，谢谢大神

**Comment by HuangXingBo** [comment]
会的。等flink 1.10完了，我有时间会写写这方面的例子。

**Comment by HuangXingBo** [comment]
@searchlink 写入mysql的例子，我放在use_case下面有个，你可以参考一下。

**Comment by HuangXingBo** [comment]
关于tensorflow on flink这块，隔壁组有个flink-ai-extended的repo，可以参考https://github.com/alibaba/flink-ai-extended
